name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTEST_ADDOPTS: "--color=yes"

permissions: {}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Build and Check Package
      uses: hynek/build-and-inspect-python-package@c52c3a4710070b50470d903818a7b25115dcd076

  build:
    needs: [package]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        name: ["ubuntu-py312"]

        include:          
          - name: "ubuntu-py312"
            python: "3.12"
            os: ubuntu-latest
            tox_env: "py312"
            use_coverage: false

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Download Package
      uses: actions/download-artifact@v5
      with:
        name: Packages
        path: dist

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
        check-latest: true
        allow-prereleases: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage

    - name: Test without coverage
      if: "! matrix.use_coverage"
      shell: bash
      run: tox run -e ${{ matrix.tox_env }} --installpkg `find dist/*.tar.gz`

  test-with-testmon:
    name: Run tests with pytest-testmon
    needs: [package]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: ["ubuntu-py312"]

        include:          
          - name: "ubuntu-py312"
            python: "3.12"
            os: ubuntu-latest
            tox_env: "py312"
            use_coverage: false
            
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Download Package
      uses: actions/download-artifact@v5
      with:
        name: Packages
        path: dist

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
        check-latest: true
        allow-prereleases: true

    - name: Restore .testmondata cache
      uses: actions/cache@v4
      with:
        path: .testmondata
        key: testmon-${{ github.ref_name }}
        restore-keys: |
          testmon-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-testmon

    - name: First run (full, builds testmon cache)
      run: |
        pip install dist/*.whl
        time pytest --testmon

    - name: Save testmon cache
      uses: actions/cache/save@v4
      with:
        path: .testmondata
        key: testmon-${{ github.ref_name }}-${{ github.run_id }}

    - name: Second run (incremental)
      run: |
        echo "Running incremental testmon pass"
        time pytest --testmon

    
